<a href="https://colab.research.google.com/github/Nihir2904/DeepLearning101/blob/main/Tensorflow_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

**Initializing a tensor**

---



In [6]:
x= tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [7]:
x= tf.constant(4, shape= (1,1))
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [8]:
x= tf.constant([[4,1,3],[1,2,3]])
print(x)

tf.Tensor(
[[4 1 3]
 [1 2 3]], shape=(2, 3), dtype=int32)


In [10]:
x= tf.ones((3,3,3))
print(x)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 3, 3), dtype=float32)


In [12]:
x= tf.random.normal((3,3), mean= 0, stddev = 1)
print(x)

tf.Tensor(
[[ 0.22904159  1.423654   -0.8563526 ]
 [-1.2458755  -0.19341734  0.19512382]
 [-0.7650945  -0.27877486  2.0201907 ]], shape=(3, 3), dtype=float32)


In [13]:
x= tf.random.uniform((1,3),minval=10,maxval=20)
print(x)

tf.Tensor([[18.431784 18.448385 18.522678]], shape=(1, 3), dtype=float32)


**Mathematical operations**

---



element wise

In [17]:
X = tf.constant([3,2,1])
Y = tf.constant([7,8,1])
Z= tf.add(X,Y)
P = tf.subtract(Y,X)
D = tf.divide(Y,X)
M = tf.multiply(Y,X)
print(Z,P,D,M)

tf.Tensor([10 10  2], shape=(3,), dtype=int32) tf.Tensor([4 6 0], shape=(3,), dtype=int32) tf.Tensor([2.33333333 4.         1.        ], shape=(3,), dtype=float64) tf.Tensor([21 16  1], shape=(3,), dtype=int32)


complete

In [21]:
X = tf.constant([3,2,1])
Y = tf.constant([7,8,1])
Z = tf.tensordot(X,Y,axes=1)
print(Z)

tf.Tensor(38, shape=(), dtype=int32)


In [23]:
z= X**2
print(z)

tf.Tensor([9 4 1], shape=(3,), dtype=int32)
